name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          curl -L https://github.com/theos/sdks/raw/master/iPhoneOS14.5.sdk.tar.xz | tar -xJ -C /opt/theos/sdks
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
          echo "/opt/theos/bin" >> $GITHUB_PATH

      - name: Build Package
        run: |
          export THEOS=/opt/theos
          make package FINALPACKAGE=1
          
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PES_Salah_Tweak
          path: packages/*.deb
