name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/opt/theos" >> $GITHUB_ENV

      - name: Build
        run: |
          cd $GITHUB_WORKSPACE
          make package FINALPACKAGE=1 THEOS_DEVICE_IP=localhost
          
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: PES_Salah_Tweak
          path: packages/*.deb
