name: Build Tweak
on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Theos
        run: |
          bash -c "$(curl -fsSL https://raw.githubusercontent.com/theos/theos/master/bin/install-theos)"
          echo "THEOS=/opt/theos" >> $GITHUB_ENV
          echo "/opt/theos/bin" >> $GITHUB_PATH

      - name: Build Package
        run: |
          export THEOS=/opt/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PES_Salah_Tweak
          path: packages/*.deb
